name: taxinet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.11
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.12
  firebase_database: ^9.0.9
  http:
  get:
  get_storage:
  badges:
  url_launcher:
  flutter_local_notifications:
  rxdart:
  dio:
  modal_bottom_sheet:
  animated_text_kit:
  file_picker:
  image_picker:
  image_cropper:
  lottie: ^1.2.2
  provider: ^6.0.2
  google_fonts: ^2.3.1
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.0.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.3
  location: ^4.3.0
  uuid: ^3.0.6
  geolocator: ^8.2.0
  flutter_google_places: ^0.3.0
  geocoding: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/json/


  fonts:
    - family: Sansita Swashed
      fonts:
        - asset: assets/fonts/SansitaSwashed-VariableFont_wght.ttf

